"use client";

import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import work1 from "../../public/work1.png";
import work2 from "../../public/work2.png";
import work3 from "../../public/work3.jpg";
import work4 from "../../public/work4.png";
import work5 from "../../public/work5.jpg";
import work6 from "../../public/work6.jpg";
import UIUX from "../../public/design.png";
import webDevelop from "../../public/code.png";
import mobileAppDev from "../../public/mobiledev.png";
import myPhoto from "../../public/photo.png";
import { motion } from "framer-motion";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { VscGithubInverted } from "react-icons/vsc";
import { FaLinkedin, FaFacebookSquare } from "react-icons/fa"; // Use a valid Facebook icon

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import url(&apos;https://fonts.googleapis.com/css2?family=Poppins:wght@100;400;700&display=swap&apos;);
        </style>
      </Head>

      <main className="font-poppins min-h-screen px-10 bg-yellow-50 dark:bg-gray-900 md:px-20 lg:px-40">
        {/* Navbar */}
        <section>
          <nav className="py-10 flex justify-between">
            <h1 className="text-black dark:text-white text-sm">Develop by Chamika Sandaru</h1>
            <ul className="flex items-center">
              <li className="text-black dark:text-white">
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-xl mx-5"
                />
              </li>
              <li>
                <a href="https://drive.google.com/file/d/1e9FzAKhhjJR_hwEWyFX5bXKrePsUo0nv/view?usp=sharing" 
                   download={"Chamika_Resume"} 
                   className="bg-yellow-400 px-4 py-2 rounded-md text-black dark:text-white">
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          {/* Hero Section */}
          <div className="text-center p-10">
            <h1 className="text-5xl font-bold text-yellow-400 md:text-6xl lg:text-7xl lg:mb-7 mb-4">Chamika Sandaru</h1>
            <h3 className="text-2xl py-2 text-black dark:text-white">Mobile Apps and Website Developer</h3>
            <p className="text-sm text-gray-400 leading-6 mx-auto md:text-md">
              Im Chamika, an aspiring web developer seeking internships. With skills in HTML, CSS, JavaScript, Java, PHP, and frameworks like React, Angular, and Flutter, I bring web and mobile ideas to life. Explore my portfolio!
            </p>
          </div>

          {/* Social Links */}
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-300">
            <a href="https://github.com/chamikaSandaru" className="text-black dark:text-white"><VscGithubInverted /></a>
            <a href="https://www.linkedin.com/in/chamika-sandaru-b57b04267/" className="text-black dark:text-white"><FaLinkedin /></a>
            <a href="https://web.facebook.com/?_rdc=1&_rdr" className="text-black dark:text-white"><FaFacebookSquare /></a>
          </div>

          {/* Profile Picture */}
          <motion.div
            initial={{ opacity: 0, scale: 0.5 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.5 }}
            className="m-auto relative bg-gradient-to-b from-yellow-200 w-80 h-80 rounded-full mt-20 overflow-hidden md:h-96 md:w-96"
          >
            <Image src={myPhoto} alt="My Photo" layout="responsive" />
          </motion.div>
        </section>

        {/*Services*/}
        <section>
          <div>
            <h2 className='text-5xl py-10 font-bold opacity-60 text-yellow-700 dark:text-white'>
              Services I Offer
            </h2>
            <p className=' text-sm py-2 text-slate-900 leading-6 dark:text-white'>
            UI/UX Design, Web Development, and Mobile App Development Services<br></br><br></br>
Enhance your digital footprint with my comprehensive services. I specialize in UI/UX design, creating intuitive and visually appealing interfaces that boost user engagement. My web development expertise ensures robust, scalable, and responsive websites tailored to your business needs. Additionally, I develop high-performance mobile applications for iOS and Android, transforming your ideas into seamless and engaging mobile experiences. Let&apos;s work together to bring your vision to life.
            </p>
          </div>

          {/*Services cards*/}
          <div className='md:flex lg-flex gap-10 mx-auto' >
            {/*UIUX*/}
            <motion.div
          whileHover={{scale:1.1}}
          whileTap={{scale:0.9}}>
            <div className=' bg-teal-400 text-center shadow-sm p-5 rounded-xl my-10 '>
              <Image src={UIUX} alt='UIUX image' width={100} height={100} className='inline'/>
              <h2 className=' text-2xl font-bold'>
                UI/UX Designing
              </h2>
              <p className='text-sm py-2 text-slate-900 leading-6'>
              &quot;Transform your digital presence with intuitive and visually stunning UI/UX design. I specialize in creating user-centric interfaces that enhance the user experience and drive engagement. From wireframing to prototyping, I ensure that every aspect of the design process is tailored to meet your specific needs and goals&quot;
              </p>
            </div>
            </motion.div>


            {/*Web Developing*/}
            <motion.div
          whileHover={{scale:1.1}}
          whileTap={{scale:0.9}}>
            <div className=' bg-teal-400 text-center shadow-sm p-5 rounded-xl my-10'>
              <Image src={webDevelop} alt='webdevelop image' width={100} height={100} className='inline'/>
              <h2 className=' text-2xl font-bold'>
                Web Develop
              </h2>
              <p className='text-sm py-2 text-slate-900 leading-6'>
              &quot;Build a robust and scalable online presence with my web development services. I provide custom web solutions tailored to your business needs, ensuring high performance, security, and seamless user experiences. From front-end design to back-end development, I create responsive and interactive websites that engage and convert visitors.&quot;
              </p>
            </div>
            </motion.div>

            {/*mobileApp Developing*/}
            <motion.div
          whileHover={{scale:1.1}}
          whileTap={{scale:0.9}}>
            <div className=' bg-teal-400 text-center shadow-sm p-5 rounded-xl my-10'>
              <Image src={mobileAppDev} alt='mobileApp image' width={100} height={100} className='inline'/>
              <h2 className=' text-2xl font-bold'>
                Mobile App Develop
              </h2>
              <p className='text-sm py-2 text-slate-900 leading-6'>
              &quot;Bring your ideas to life with top-notch mobile 
              app development. I specialize in creating intuitive and high-performance mobile applications for both iOS and Android platforms. From concept to deployment, I ensure your app is user-friendly, feature-rich, and tailored to meet your specific business needs. Transform your vision into a seamless mobile experience that engages users and drives results.&quot;
              </p>
            </div>  
            </motion.div>

          </div>
        </section>

        {/*my work*/}
        <section>
          <div>
            <h2 className='text-5xl py-10 font-bold opacity-60  text-yellow-700 dark:text-white'>
              Portfolio
            </h2>
            <p className='text-sm py-2 text-slate-900 leading-6 dark:text-white'>
            &quot;Dive into my portfolio to witness the fusion of design and functionality. 
            As a UI/UX designer and web developer, 
            my work reflects a commitment to creating engaging and seamless digital experiences. 
            Explore and envision the possibilities.&quot;
            </p>
          </div><br></br>
          {/*my work images*/}
          <h1 className=' text-sm md:text-xl  text-yellow-500 dark:text-white' >UI | UX Designs</h1>
          <div className='flex flex-col gap-10 p-10 lg:flex-row lg:flex-wrap'>
            <div className=' basis-1/3 flex-1'><motion.div
          whileHover={{scale:1.1 , rotate:3}}
          whileTap={{scale:0.8 , rotate:-10 , borderRadius:"100%"}}><Image src={work1} alt='work1' layout='responsive' className='rounded-lg object-cover'/></motion.div></div>
            <div className=' basis-1/3 flex-1'><motion.div
          whileHover={{scale:1.1 , rotate:3}}
          whileTap={{scale:0.8 , rotate:-10 , borderRadius:"100%"}}><Image src={work4} alt='work4' layout='responsive' className='rounded-lg object-cover'/></motion.div></div>
            </div>

            <br></br><h1 className=' text-sm md:text-xl text-yellow-500 dark:text-white' >Mobile App Development</h1><br></br>
            <div className='flex flex-col gap-10 p-10 lg:flex-row lg:flex-wrap'>
            <div className=' basis-1/3 flex-1'><motion.div
          whileHover={{scale:1.1 , rotate:3}}
          whileTap={{scale:0.8 , rotate:-10 , borderRadius:"100%"}}><Image src={work2} alt='work2' layout='responsive' className='rounded-lg object-cover'/></motion.div></div>
            <div className=' basis-1/3 flex-1'><motion.div
          whileHover={{scale:1.1 , rotate:3}}
          whileTap={{scale:0.8 , rotate:-10 , borderRadius:"100%"}}><Image src={work3} alt='work3' layout='responsive' className='rounded-lg object-cover'/></motion.div></div>
            </div>

            <br></br><h1 className=' text-sm md:text-xl text-yellow-500 dark:text-white' >Web Development</h1><br></br>
            <div className='flex flex-col gap-10 p-10 lg:flex-row lg:flex-wrap'>
            <div className=' basis-1/3 flex-1'><motion.div
          whileHover={{scale:1.1 , rotate:3}}
          whileTap={{scale:0.8 , rotate:-10 , borderRadius:"100%"}}><Image src={work6} alt='work2' layout='responsive' className='rounded-lg object-cover'/></motion.div></div>
            <div className=' basis-1/3 flex-1'><motion.div
          whileHover={{scale:1.1 , rotate:3}}
          whileTap={{scale:0.8 , rotate:-10 , borderRadius:"100%"}}><Image src={work5} alt='work3' layout='responsive' className='rounded-lg object-cover'/></motion.div></div>
            </div>
        </section>

        {/* Footer */}
        <footer className="border-t-2 border-black dark:border-gray-400 text-sm opacity-70 flex flex-col gap-10 mt-5 items-center justify-center py-10 text-gray-400 lg:flex-row lg:justify-between">
          <div>
            <h3 className="text-base mb-5 text-black dark:text-white">Contact me for more details</h3>
            <p className="opacity-60 mt-5 text-black dark:text-white">
              Let&apos;s discuss potential collaboration and project ideas! <h3 className="opacity-80 text-black dark:text-white">0779930726</h3>
            </p>
          </div>
        </footer>
      </main>
    </div>
  );
}
